### ISSUE TITLE
model can't be run on Replicate

### ISSUE THREAD

**Issue by musowir** [NohaMoAmary/image-description-base-model#1]
I've tried to run your model on  Replicate and it showed this:-

"😵 Uh oh! This model can't be run on Replicate because it was built with a version of Cog that is no longer supported. Consider opening an issue on [the model's GitHub repository](https://github.com/NohaMoAmary/image-captioning-with-visual-attention.git) to see if it can be updated to use [a recent version of Cog](https://github.com/replicate/cog).."

![Screenshot](https://user-images.githubusercontent.com/68455903/225802712-bc08506d-97c6-42a2-bf55-375c34404b32.png)

**Comment by NohaMoAmary** [comment]
i solve the problem 
you can run the model now
